---
- hosts: rpi
  vars_files:
      - vars.yaml

  tasks:
      #- name: Include variables

    - name: shutdown server
      command: sudo a2dissite prod
      become: yes
      ignore_errors: yes

    - name: remove letter frequency (name_gen)
      become: yes
      file: 
          path: "{{ base_path }}/services/name_gen/name_generator/letter.freq"
          state: absent
    - name: remove map (name_gen)
      become: yes
      file:
          path: "{{ base_path }}/services/name_gen/name_generator/n2a.map"
          state: absent

    - name: sync files
      become: yes
      synchronize:
        src: "{{ base_path }}"
        dest: "{{ base_path }}"
        rsync_opts:
          - '--chmod=ug=rwX'
          - '--chown=www-data:www-data'

    - name: run mysql files
      script: 
          cmd: mysql < "{{ base_path }}/configs/board_games.mysql"; mysql < "{{ base_path }}/configs/rpg.mysql"
          become: yes
      ignore_errors: yes


    - name: enable server
      command: sudo a2ensite prod.conf
      become: yes

    - name: restart server
      command: sudo service apache2 restart
      become: yes
